name: Deploy Infrastructure

on:
    push:
        branches:
            - main

jobs:
    terraform:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::914559461558:role/GithubActions
                aws-region: eu-north-1

            - name: Build Docker image
              run: docker build -t myflaskapp ./App/flask_app

            - name: Authenticate to Amazon ECR
              run: |
                aws ecr get-login-password --region eu-north-1 \
                  | docker login --username AWS --password-stdin 914559461558.dkr.ecr.eu-north-1.amazonaws.com

            - name: Tag Docker image
              run: docker tag myflaskapp:latest 914559461558.dkr.ecr.eu-north-1.amazonaws.com/myflaskapp:latest

            - name: Push Docker image to ECR
              run: docker push 914559461558.dkr.ecr.eu-north-1.amazonaws.com/myflaskapp:latest

        
            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan -var-file=dev.tfvars

            # - name: Terraform Destroy              
            #   run: terraform destroy -auto-approve -var-file=dev.tfvars

            - name: Terraform Apply
              env:
                TF_LOG: DEBUG
              run: terraform apply -auto-approve -var-file=dev.tfvars
                
            - name: Terraform Total Output
              run: terraform state list

           