name: Deploy - Dev - Infrastructure

on:
    push:
        branches:
            - dev
    workflow_dispatch:
      inputs:
        action:
            description: 'Select action to perform'
            required: true
            default: 'apply'
            type: choice
            options:
                - apply
                - destroy

jobs:
    terraform:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::604312263409:role/githubuser
                aws-region: eu-north-1

            - name: Create s3 bucket for backend
              run: |
                 aws s3api head-bucket --bucket dev-tf-state-bucket-11-08-2025 2>/dev/null || \
                  aws s3api create-bucket \
                      --bucket dev-tf-state-bucket-11-08-2025 \
                      --region eu-north-1 \
                      --create-bucket-configuration LocationConstraint=eu-north-1

            - name: Delete cached terraform modules
              run: | 
               rm -rf .terraform/modules
               terraform get -update

            - name: Terraform  Init
              run: terraform -chdir=environments/dev init -backend-config="bucket=dev-tf-state-bucket-11-08-2025"

            - name: Terraform Validate
              run: terraform validate
                

            - name: Terraform Plan
              run: |
                export TF_LOG=DEBUG 
                terraform -chdir=environments/dev plan -var-file=dev.tfvars

            - name: Terraform -Destroy 
              if: ${{ github.event.inputs.action == 'destroy' }}             
              run: terraform -chdir=environments/dev destroy --auto-approve -var-file=dev.tfvars


            - name: Terraform Apply
              if: ${{ github.event.inputs.action == 'apply' }}
              env:
                TF_LOG: DEBUG
              run: terraform -chdir=environments/dev apply --auto-approve -var-file=dev.tfvars

                
            - name: Terraform Total Output
              run: terraform -chdir=environments/dev state list

           